### ISSUE TITLE
Enable builds on travis

### ISSUE THREAD

**Issue by byorgey** [cchalmers/texrunner#9]
We have a `.travis.yml` but the repository is not enabled on `travis-ci.org`.  I think you should be able to visit `travis-ci.org/cchalmers/texrunner` and hit a button to turn it on.

**Comment by cchalmers** [comment]
I've pressed enable but nothing appeared to happen. Is there anything else I need to do?

**Comment by byorgey** [comment]
Nope, that worked great!  It doesn't actually trigger a build until the next push. But it's running now: https://travis-ci.org/cchalmers/texrunner/builds/611835033
